---
title: "p8105_hw1_sjk2254"
output: github_document
author: "Sharon Kulali"
date: "2023-09-18"
---

# Problem 1

loading the needed packages

```{r setup, include=FALSE}
library(moderndive)
library(tidyverse)
data(early_january_weather)
```

assessing the dataset help file

```{r}
?early_january_weather
```

```{r}
nrow(early_january_weather)
```

```{r}
ncol(early_january_weather)
```



Information about the dataset: The s``



creating the scatterplot

```{r}
ggplot(data = early_january_weather, aes(x = time_hour, y = temp, color = humid)) +
  geom_point() + ggtitle("Temp vs Time (Hours)")
```

saving the scatterplot

```{r}
ggsave("scatter_plot_p1.pdf", height = 4, width = 6)
```

# Problem #2

```{r}
p2_df = tibble(
     num_samp = rnorm(10),
     log_vec = num_samp > 0,
     chr_vec = c("female","female","unisex","unisex","male","male","female","male","unisex","female"),
     fct_vec = factor(chr_vec)
)
```

```{r}
m_num_samp = mean(pull(p2_df, num_samp))
```

```{r}
m_log_vec = mean(pull(p2_df, log_vec))
```

```{r}
m_chr_vec = mean(pull(p2_df, chr_vec))
```

```{r}
m_fct_vec = mean(pull(p2_df, fct_vec))
```

the character and factor vectors didn't work

```{r}
an_log_vec = as.numeric(pull(p2_df,log_vec))
mean(an_log_vec)

an_chr_vec = as.numeric(pull(p2_df,chr_vec))
mean(an_chr_vec)

an_fct_vec = as.numeric(pull(p2_df,fct_vec))
mean(an_fct_vec)
```

because are stored are stored as integers while characters are stored as words